/** Evidence Ledger Stage 03: retains resource-input and KNOWN/UNKNOWN state handlers. */
import React from "react";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { DataAvailability } from "../../../types/v2";
import { OracleButton } from "../OracleButton";
import { OracleInput } from "../OracleInput";
import { IntakeFormData } from "./types";

export interface OracleExecutionCapacityProps { formData: IntakeFormData; updateForm: (updates: Partial<IntakeFormData>) => void; onNext: () => void; onBack: () => void; }

export const OracleExecutionCapacity: React.FC<OracleExecutionCapacityProps> = ({ formData, updateForm, onNext, onBack }) => {
  const handleEpistemicHours = (state: DataAvailability, val?: string) => updateForm({ availableWeeklyHours: { value: val !== undefined ? val : formData.availableWeeklyHours.value, state } });
  const handleEpistemicYears = (state: DataAvailability, val?: string) => updateForm({ experienceYears: { value: val !== undefined ? val : formData.experienceYears.value, state } });
  const numberRow = (id: string, label: string, guidance: string, state: "hours" | "years") => {
    const item = state === "hours" ? formData.availableWeeklyHours : formData.experienceYears;
    const handler = state === "hours" ? handleEpistemicHours : handleEpistemicYears;
    const placeholder = state === "hours" ? "40" : "5";
    return <section className="grid gap-4 border-t border-[var(--oracle-border)] py-6 sm:grid-cols-[minmax(0,1fr)_220px]"><div><label htmlFor={id} className="text-sm font-extrabold text-[var(--oracle-text-primary)]">{label}</label><p className="mt-1 text-[11px] leading-5 text-[var(--oracle-text-muted)]">{guidance}</p></div><div><div className="flex gap-1.5"><button type="button" onClick={() => handler("KNOWN")} className={`min-h-[36px] border px-2.5 text-[10px] font-extrabold tracking-[0.06em] ${item.state === "KNOWN" ? "border-[var(--oracle-immutable-border)] bg-[var(--oracle-immutable-bg)] text-[var(--oracle-immutable)]" : "border-transparent text-[var(--oracle-text-muted)]"}`}>KNOWN</button><button type="button" onClick={() => handler("UNKNOWN")} className={`min-h-[36px] border px-2.5 text-[10px] font-extrabold tracking-[0.06em] ${item.state === "UNKNOWN" ? "border-[var(--oracle-unknown-border)] bg-[var(--oracle-unknown-bg)] text-[var(--oracle-unknown)]" : "border-transparent text-[var(--oracle-text-muted)]"}`}>UNKNOWN</button></div><input id={id} type="text" inputMode="numeric" disabled={item.state !== "KNOWN"} value={item.state === "KNOWN" ? item.value : ""} onChange={(e) => handler("KNOWN", e.target.value)} placeholder={item.state === "KNOWN" ? placeholder : "Unknown"} className={`mt-3 w-full border py-3 px-3 font-mono text-sm text-[var(--oracle-text-primary)] placeholder:text-[var(--oracle-text-muted)] focus:outline-none focus:ring-1 ${item.state === "KNOWN" ? "border-[var(--oracle-border-strong)] bg-[var(--oracle-surface)] focus:border-[var(--oracle-action)] focus:ring-[var(--oracle-action)]" : "border-[var(--oracle-unknown-border)] bg-[var(--oracle-unknown-bg)]"}`} /></div></section>;
  };
  return <div className="mx-auto grid w-full max-w-7xl gap-10 px-4 py-10 sm:px-6 sm:py-14 lg:grid-cols-[minmax(0,1fr)_250px] lg:gap-20 lg:px-8"><main><header className="border-b border-[var(--oracle-border)] pb-9"><p className="oracle-kicker">03 / Execution Capacity</p><h1 className="oracle-display mt-4 max-w-[17ch] text-4xl leading-[1.02] sm:text-5xl">Measure the capacity the decision can actually draw on.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-[var(--oracle-text-secondary)]">The record distinguishes time, relevant experience, and support from the ambition of the decision itself.</p></header><section className="mt-8"><div className="border-y border-[var(--oracle-border)]">{numberRow("weekly-hours", "Available Dedicated Hours Per Week", "Realistically sustained hours per week without immediate burnout or health degradation.", "hours")}{numberRow("experience-years", "Relevant Domain Experience (Years)", "Directly applicable years in the industry, discipline, or operational craft.", "years")}</div><div className="mt-8 grid gap-6 border-t border-[var(--oracle-border)] pt-7"><OracleInput label="Relevant Core Skills" hint="Comma-separated capabilities relevant to this decision." value={formData.relevantSkills} onChange={(e) => updateForm({ relevantSkills: e.target.value })} placeholder="Full-Stack TypeScript, Distributed Systems, ML Engineering" /><OracleInput label="Support Network & Mentors" hint="Advisors, technical collaborators, investor connections, or peers." value={formData.availableSupportNetwork} onChange={(e) => updateForm({ availableSupportNetwork: e.target.value })} placeholder="3 SaaS Founder Mentors, 2 Angel Investors, Technical Community" /><OracleInput label="Available Physical Assets & Tools" hint="Dedicated workspace, hardware, licences, or existing production infrastructure." value={formData.availablePhysicalAssets} onChange={(e) => updateForm({ availablePhysicalAssets: e.target.value })} placeholder="Home Office Setup, Dedicated Compute Servers" /></div><footer className="mt-9 flex items-center justify-between border-t border-[var(--oracle-border)] pt-8"><OracleButton variant="secondary" size="md" onClick={onBack} leftIcon={<ArrowLeft className="h-4 w-4" />}>Back</OracleButton><OracleButton variant="primary" size="lg" onClick={onNext} rightIcon={<ArrowRight className="h-4 w-4" />}>Continue to Commitments</OracleButton></footer></section></main><aside className="hidden border-l border-[var(--oracle-border)] pl-6 lg:block"><div className="sticky top-40"><p className="oracle-kicker">Stage intent</p><p className="oracle-display mt-3 text-2xl leading-tight">A plan needs available capacity, not assumed capacity.</p><p className="mt-5 text-xs leading-5 text-[var(--oracle-text-muted)]">Use your sustained baseline rather than an aspirational maximum. Mark a figure unknown when it is genuinely unavailable.</p></div></aside></div>;
};
