/** Evidence Ledger Stage 05: retains evidence and assumption add/remove behavior. */
import React, { useState } from "react";
import { ArrowLeft, ArrowRight, Plus, Trash2 } from "lucide-react";
import { AssumptionItem, EvidenceItem } from "../../../types/v2";
import { OracleButton } from "../OracleButton";
import { OracleInput } from "../OracleInput";
import { IntakeFormData } from "./types";

export interface OracleEvidenceBaselineProps { formData: IntakeFormData; updateForm: (updates: Partial<IntakeFormData>) => void; onNext: () => void; onBack: () => void; }

export const OracleEvidenceBaseline: React.FC<OracleEvidenceBaselineProps> = ({ formData, updateForm, onNext, onBack }) => {
  const stageIdentity = "05 / Evidence & Baseline";
  const [newEvidenceDesc, setNewEvidenceDesc] = useState("");
  const [newAssumptionStmt, setNewAssumptionStmt] = useState("");
  const handleAddEvidence = () => { if (!newEvidenceDesc.trim()) return; const item: EvidenceItem = { id: `ev_${Date.now()}`, sourceType: "USER_STATEMENT", description: newEvidenceDesc.trim(), verificationStatus: "USER_PROVIDED", relevance: "DIRECT", confidenceClassification: "MEDIUM", supportsVariables: ["decision.decisionStatement"] }; updateForm({ evidenceItems: [...formData.evidenceItems, item] }); setNewEvidenceDesc(""); };
  const handleRemoveEvidence = (id: string) => updateForm({ evidenceItems: formData.evidenceItems.filter((ev) => ev.id !== id) });
  const handleAddAssumption = () => { if (!newAssumptionStmt.trim()) return; const item: AssumptionItem = { id: `asm_${Date.now()}`, statement: newAssumptionStmt.trim(), relatedVariable: "decision.desiredOutcome", source: "USER_STATED", confidence: "MEDIUM", impactIfChanged: "HIGH" }; updateForm({ assumptionItems: [...formData.assumptionItems, item] }); setNewAssumptionStmt(""); };
  const handleRemoveAssumption = (id: string) => updateForm({ assumptionItems: formData.assumptionItems.filter((asm) => asm.id !== id) });
  const ledger = (kind: "evidence" | "assumption") => {
    const isEvidence = kind === "evidence"; const items = isEvidence ? formData.evidenceItems : formData.assumptionItems; const draft = isEvidence ? newEvidenceDesc : newAssumptionStmt; const setDraft = isEvidence ? setNewEvidenceDesc : setNewAssumptionStmt; const add = isEvidence ? handleAddEvidence : handleAddAssumption; const remove = isEvidence ? handleRemoveEvidence : handleRemoveAssumption; const title = isEvidence ? "WHAT I KNOW — EVIDENCE & RECORDS" : "WHAT I ASSUME — WORKING HYPOTHESES"; const tone = isEvidence ? "var(--oracle-provenance)" : "var(--oracle-estimated)";
    return <section className="border-t border-[var(--oracle-border)] pt-6"><div className="border-l-2 pl-4" style={{ borderColor: tone }}><p className="text-[11px] font-extrabold tracking-[0.05em] text-[var(--oracle-text-primary)]">{title}</p><p className="mt-1 text-[11px] leading-5 text-[var(--oracle-text-muted)]">{isEvidence ? "Confirmed records, balances, contracts, or third-party validation." : "Working conditions supplied for the decision record; they remain visibly distinct from evidence."}</p></div><div className="mt-4 divide-y divide-[var(--oracle-border-subtle)] border-y border-[var(--oracle-border)]">{items.map((item) => <div key={item.id} className="flex items-start justify-between gap-3 px-1 py-3"><div><p className="text-xs font-bold text-[var(--oracle-text-primary)]">{isEvidence ? (item as EvidenceItem).description : (item as AssumptionItem).statement}</p><p className="oracle-technical mt-1" style={{ color: tone }}>{isEvidence ? `${(item as EvidenceItem).verificationStatus.replace(/_/g, " ")} · ${(item as EvidenceItem).confidenceClassification} CONFIDENCE` : `${(item as AssumptionItem).confidence} CONFIDENCE · ${(item as AssumptionItem).impactIfChanged} IMPACT`}</p></div><button type="button" onClick={() => remove(item.id)} aria-label={`Remove ${isEvidence ? "evidence" : "assumption"}`} className="grid h-9 w-9 shrink-0 place-items-center text-[var(--oracle-text-muted)] hover:text-[var(--oracle-risk)]"><Trash2 className="h-4 w-4" /></button></div>)}</div><div className="mt-3 flex gap-2"><input type="text" value={draft} onChange={(e) => setDraft(e.target.value)} onKeyDown={(e) => e.key === "Enter" && (e.preventDefault(), add())} placeholder={isEvidence ? "Add confirmed evidence fact..." : "Add working assumption..."} className="min-h-[44px] flex-1 border border-[var(--oracle-border-strong)] bg-[var(--oracle-surface)] px-3 text-xs text-[var(--oracle-text-primary)] placeholder:text-[var(--oracle-text-muted)] focus:border-[var(--oracle-action)] focus:outline-none" /><button type="button" onClick={add} aria-label={`Add ${isEvidence ? "evidence" : "assumption"}`} className="grid h-11 w-11 place-items-center border border-[var(--oracle-border-strong)] bg-[var(--oracle-surface-subtle)] text-[var(--oracle-text-primary)] hover:border-[var(--oracle-action)] hover:text-[var(--oracle-action)]"><Plus className="h-4 w-4" /></button></div></section>;
  };
  return <div className="mx-auto grid w-full max-w-7xl gap-10 px-4 py-10 sm:px-6 sm:py-14 lg:grid-cols-[minmax(0,1fr)_250px] lg:gap-20 lg:px-8"><main><header className="border-b border-[var(--oracle-border)] pb-9"><p className="oracle-kicker">{stageIdentity}</p><h1 className="oracle-display mt-4 max-w-[17ch] text-4xl leading-[1.02] sm:text-5xl">Separate what you know from what you are assuming.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-[var(--oracle-text-secondary)]">Evidence and working assumptions are both useful to a serious decision record—but they must never be visually or semantically conflated.</p></header><section className="mt-8"><div className="grid gap-6"><OracleInput label="Primary Market / Growth Thesis" hint="The core economic or strategic mechanism that creates upside." value={formData.primaryOpportunity} onChange={(e) => updateForm({ primaryOpportunity: e.target.value })} placeholder="e.g. B2B Enterprise Decision Simulation Software SaaS" /><OracleInput label="Opportunity Cost Summary" hint="What valuable alternative is being traded away?" value={formData.opportunityCostSummary} onChange={(e) => updateForm({ opportunityCostSummary: e.target.value })} placeholder="e.g. Foregoing approximately $102k in base salary annually plus career stability" /><OracleInput label="Foregone Benefits & Protections" hint="For example: healthcare, matching, unvested equity, or a predictable promotion path." value={formData.foregoneBenefits} onChange={(e) => updateForm({ foregoneBenefits: e.target.value })} placeholder="Corporate healthcare matching, Annual equity vesting, Predictable bonus" /></div><div className="mt-9 grid gap-8 border-y border-[var(--oracle-border)] py-2 lg:grid-cols-2 lg:gap-10">{ledger("evidence")}{ledger("assumption")}</div><footer className="mt-9 flex items-center justify-between border-t border-[var(--oracle-border)] pt-8"><OracleButton variant="secondary" size="md" onClick={onBack} leftIcon={<ArrowLeft className="h-4 w-4" />}>Back</OracleButton><OracleButton variant="primary" size="lg" onClick={onNext} rightIcon={<ArrowRight className="h-4 w-4" />}>Review Decision</OracleButton></footer></section></main><aside className="hidden border-l border-[var(--oracle-border)] pl-6 lg:block"><div className="sticky top-40"><p className="oracle-kicker">Stage intent</p><p className="oracle-display mt-3 text-2xl leading-tight">The evidence boundary protects the quality of the reasoning.</p><p className="mt-5 text-xs leading-5 text-[var(--oracle-text-muted)]">Add only the evidence and assumptions you can articulate. They remain separately identified after submission.</p></div></aside></div>;
};
