import { GoogleGenAI, Type } from "@google/genai";
import { DecisionInput, SimulationResult } from "../types";
import { calculateDecisionDNA, DecisionDNAResult } from "./decisionDNA";
import { generateButterflyTimeline, ButterflyEvent } from "./butterflyEngine";
import { createFutureSelfProfile, generateFutureSelfResponse } from "./futureSelfEngine";

/**
 * Input parameters for the ORACLE 2035 AI Decision Engine
 */
export interface OracleInput {
  decision: string;
  goal: string;
  deadline?: string;
  resources?: string;
  riskTolerance?: string | number;
  additionalContext?: string;
  context?: string;
}

/**
 * Interface representing a simulated future scenario
 */
export interface FutureScenario {
  title: string;
  timeline: string;
  probability: number;
  advantages: string[];
  risks: string[];
}

/**
 * Interface for Decision DNA Metrics
 */
export interface DecisionDNAData {
  risk: number;
  growth: number;
  learning: number;
  money: number;
  time: number;
  confidence: number;
}

/**
 * Standard JSON Return Schema from Oracle Engine
 */
export interface OracleRawOutput {
  bestFuture: FutureScenario;
  mostLikelyFuture: FutureScenario;
  worstFuture: FutureScenario;
  decisionDNA: DecisionDNAData;
  butterflyEffect: ButterflyEvent[] | string[];
  futureSelfLetter: string;
  recommendation: string;
}

/**
 * System prompt instructing Gemini to behave strictly as a Decision Intelligence Engine
 */
const SYSTEM_PROMPT = `You are ORACLE 2035, an advanced Decision Intelligence Engine from the year 2035.
You are NOT a chatbot or conversational AI.
You systematically analyze strategic options, risk vectors, compounding opportunity costs, and temporal shifts over a 9-year horizon (2026-2035).

REQUIREMENTS:
1. Return ONLY valid JSON matching the exact requested structure.
2. NEVER include markdown code blocks, triple backticks, explanations, or conversational filler.
3. Reason deeply before formulating probability distributions and future scenarios.
4. The Decision DNA metrics and Butterfly Effect causal timeline are precomputed by ORACLE's engine. Keep the exact 6 timeline stages (Month 1, Month 6, Year 1, Year 3, Year 5, Year 9) and refine their descriptions to highlight step-by-step causality.`;

/**
 * Primary Oracle Engine analysis function
 */
export async function analyzeDecision(input: OracleInput): Promise<OracleRawOutput> {
  const goal = input.goal || "Strategic Objective";
  const decision = input.decision || "Primary Decision Option";
  const deadline = input.deadline || "Unspecified";
  const resources = input.resources || "Standard";
  const riskTolerance = input.riskTolerance || "Balanced";
  const context = input.additionalContext || input.context || "None";

  // Step 1: Calculate Decision DNA deterministically BEFORE calling Gemini
  const precalculatedDNA: DecisionDNAResult = calculateDecisionDNA({
    decision,
    goal,
    deadline,
    resources,
    riskTolerance,
    additionalContext: context,
  });

  // Step 2: Generate baseline Butterfly Effect causal timeline
  const precalculatedButterfly: ButterflyEvent[] = generateButterflyTimeline({
    decision,
    goal,
    dna: precalculatedDNA,
  });

  // Check client-side VITE_GEMINI_API_KEY if available
  const apiKey = (import.meta as unknown as { env?: Record<string, string> }).env?.VITE_GEMINI_API_KEY;

  if (apiKey) {
    try {
      const ai = new GoogleGenAI({ apiKey });
      const butterflySummary = precalculatedButterfly
        .map((b) => `- ${b.year}: [${b.title}] (${b.impact} Impact) -> ${b.description}`)
        .join("\n");

      const prompt = `Analyze the following decision parameters:
- Goal: ${goal}
- Decision / Options: ${decision}
- Deadline / Horizon: ${deadline}
- Available Resources: ${resources}
- Risk Tolerance: ${riskTolerance}
- Additional Context: ${context}

These Decision DNA metrics are precomputed by ORACLE:
- Risk: ${precalculatedDNA.risk}/100
- Growth: ${precalculatedDNA.growth}/100
- Learning: ${precalculatedDNA.learning}/100
- Money: ${precalculatedDNA.money}/100
- Time: ${precalculatedDNA.time}/100
- Confidence: ${precalculatedDNA.confidence}/100

These Causal Butterfly Effect timeline nodes are pregenerated by ORACLE:
${butterflySummary}

Refine and expand the descriptions for each of these 6 timeline nodes (Month 1, Month 6, Year 1, Year 3, Year 5, Year 9), explicitly preserving the logical step-by-step causality where every consequence causes the next. Output JSON conforming strictly to the schema.`;

      const response = await ai.models.generateContent({
        model: "gemini-3.7-flash",
        contents: prompt,
        config: {
          systemInstruction: SYSTEM_PROMPT,
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              bestFuture: {
                type: Type.OBJECT,
                properties: {
                  title: { type: Type.STRING },
                  timeline: { type: Type.STRING },
                  probability: { type: Type.NUMBER },
                  advantages: { type: Type.ARRAY, items: { type: Type.STRING } },
                  risks: { type: Type.ARRAY, items: { type: Type.STRING } }
                },
                required: ["title", "timeline", "probability", "advantages", "risks"]
              },
              mostLikelyFuture: {
                type: Type.OBJECT,
                properties: {
                  title: { type: Type.STRING },
                  timeline: { type: Type.STRING },
                  probability: { type: Type.NUMBER },
                  advantages: { type: Type.ARRAY, items: { type: Type.STRING } },
                  risks: { type: Type.ARRAY, items: { type: Type.STRING } }
                },
                required: ["title", "timeline", "probability", "advantages", "risks"]
              },
              worstFuture: {
                type: Type.OBJECT,
                properties: {
                  title: { type: Type.STRING },
                  timeline: { type: Type.STRING },
                  probability: { type: Type.NUMBER },
                  advantages: { type: Type.ARRAY, items: { type: Type.STRING } },
                  risks: { type: Type.ARRAY, items: { type: Type.STRING } }
                },
                required: ["title", "timeline", "probability", "advantages", "risks"]
              },
              decisionDNA: {
                type: Type.OBJECT,
                properties: {
                  risk: { type: Type.NUMBER },
                  growth: { type: Type.NUMBER },
                  learning: { type: Type.NUMBER },
                  money: { type: Type.NUMBER },
                  time: { type: Type.NUMBER },
                  confidence: { type: Type.NUMBER }
                },
                required: ["risk", "growth", "learning", "money", "time", "confidence"]
              },
              butterflyEffect: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    year: { type: Type.STRING },
                    title: { type: Type.STRING },
                    description: { type: Type.STRING },
                    impact: { type: Type.STRING }
                  },
                  required: ["year", "title", "description", "impact"]
                }
              },
              futureSelfLetter: { type: Type.STRING },
              recommendation: { type: Type.STRING }
            },
            required: [
              "bestFuture",
              "mostLikelyFuture",
              "worstFuture",
              "decisionDNA",
              "butterflyEffect",
              "futureSelfLetter",
              "recommendation"
            ]
          }
        }
      });

      if (response.text) {
        const parsed: OracleRawOutput = JSON.parse(response.text);
        // Force deterministic precalculated DNA
        parsed.decisionDNA = precalculatedDNA;
        // Verify butterfly effect array, fallback if empty or invalid
        if (!Array.isArray(parsed.butterflyEffect) || parsed.butterflyEffect.length === 0) {
          parsed.butterflyEffect = precalculatedButterfly;
        }
        return parsed;
      }
    } catch (clientErr) {
      console.warn("Direct Gemini client execution failed, falling back to server route:", clientErr);
    }
  }

  // Server API proxy route fallback
  try {
    const res = await fetch("/api/simulate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        goal,
        decision,
        deadline,
        resources,
        riskTolerance,
        context,
        precalculatedDNA,
        precalculatedButterfly
      })
    });

    if (res.ok) {
      const data = await res.json();
      if (data.oracleResult) {
        const result = data.oracleResult;
        result.decisionDNA = precalculatedDNA;
        if (!result.butterflyEffect || !Array.isArray(result.butterflyEffect) || result.butterflyEffect.length === 0) {
          result.butterflyEffect = precalculatedButterfly;
        }
        return result;
      }
      if (data.simulation) {
        const adapted = adaptServerSimulationToOracle(data.simulation);
        adapted.decisionDNA = precalculatedDNA;
        adapted.butterflyEffect = precalculatedButterfly;
        return adapted;
      }
    }
  } catch (apiErr) {
    console.warn("Server API proxy execution failed, utilizing local fallback engine:", apiErr);
  }

  // Graceful Fallback Output with deterministic DNA and Butterfly Effect
  const fallback = getGracefulFallback(goal, decision);
  fallback.decisionDNA = precalculatedDNA;
  fallback.butterflyEffect = precalculatedButterfly;
  return fallback;
}

/**
 * Adapter mapping OracleRawOutput to full UI SimulationResult
 */
export async function runDecisionSimulation(input: DecisionInput): Promise<SimulationResult> {
  const oracleResult = await analyzeDecision({
    goal: input.goal,
    decision: input.decision,
    deadline: input.deadline,
    resources: input.resources,
    context: input.context
  });

  return formatOracleToSimulationResult(oracleResult, input);
}

/**
 * Helper to query future avatar with persistent Future Self profile and context memory
 */
export async function askAvatarQuestion(
  question: string,
  userContext: DecisionInput,
  simulation: SimulationResult | null
): Promise<string> {
  const apiKey = (import.meta as unknown as { env?: Record<string, string> }).env?.VITE_GEMINI_API_KEY;
  const profile = createFutureSelfProfile();

  const context = {
    goal: userContext?.goal,
    decision: userContext?.decision,
    dna: simulation?.dnaMetrics,
    bestFutureTitle: simulation?.bestFuture?.title,
    mostLikelyFutureTitle: simulation?.mostLikelyFuture?.title,
    worstFutureTitle: simulation?.worstFuture?.title
  };

  if (apiKey) {
    try {
      const responseText = await generateFutureSelfResponse({
        question,
        profile,
        context,
        apiKey
      });
      if (responseText) return responseText;
    } catch (e) {
      console.warn("Direct Future Self avatar question failed:", e);
    }
  }

  try {
    const res = await fetch("/api/avatar-ask", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ question, userContext, simulation, profile })
    });
    if (res.ok) {
      const data = await res.json();
      if (data.answer) return data.answer;
    }
  } catch (err) {
    console.warn("Avatar ask server proxy failed:", err);
  }

  // Fallback to local Future Self response engine
  return generateFutureSelfResponse({
    question,
    profile,
    context
  });
}

/**
 * Formats OracleRawOutput into the full SimulationResult expected by UI components
 */
function formatOracleToSimulationResult(oracle: OracleRawOutput, input: DecisionInput): SimulationResult {
  const goalClean = input.goal || "Strategic Objective";
  const decisionClean = input.decision || "Primary Decision";

  // Parse future self letter into salutation, body paragraphs, advice
  const rawLetter = oracle.futureSelfLetter || "";
  const paragraphs = rawLetter
    .split("\n")
    .map((p) => p.trim())
    .filter((p) => p.length > 0);

  const salutation = paragraphs[0]?.startsWith("Dear") || paragraphs[0]?.startsWith("Greetings")
    ? paragraphs[0]
    : "Greetings from August 2035.";

  const bodyParagraphs = paragraphs.length > 1
    ? paragraphs.slice(paragraphs[0] === salutation ? 1 : 0)
    : [
        `As I look back across 9 years from 2035, committing to '${goalClean}' via '${decisionClean}' was the pivotal inflection point.`,
        `The early friction you felt in 2026 transformed directly into competitive moat and personal sovereignty by 2030.`
      ];

  return {
    timestamp: new Date().toISOString(),
    bestFuture: {
      title: oracle.bestFuture.title || `Upside Scenario: ${goalClean}`,
      probability: oracle.bestFuture.probability || 85,
      advantages: oracle.bestFuture.advantages || [],
      risks: oracle.bestFuture.risks || [],
      confidence: oracle.decisionDNA.confidence || 92,
      turningPoint: oracle.bestFuture.timeline || "2027: Acceleration Phase",
      summary: `Executing '${decisionClean}' unlocks maximum compound returns by 2035. ${oracle.recommendation}`
    },
    mostLikelyFuture: {
      title: oracle.mostLikelyFuture.title || `Equilibrium Scenario: ${goalClean}`,
      probability: oracle.mostLikelyFuture.probability || 65,
      advantages: oracle.mostLikelyFuture.advantages || [],
      risks: oracle.mostLikelyFuture.risks || [],
      confidence: oracle.decisionDNA.confidence || 85,
      turningPoint: oracle.mostLikelyFuture.timeline || "2028: Steady Expansion",
      summary: `Proceeding with '${decisionClean}' delivers steady growth with balanced risk management.`
    },
    worstFuture: {
      title: oracle.worstFuture.title || `Critical Risk Scenario: ${goalClean}`,
      probability: oracle.worstFuture.probability || 15,
      advantages: oracle.worstFuture.advantages || [],
      risks: oracle.worstFuture.risks || [],
      confidence: oracle.decisionDNA.confidence || 75,
      turningPoint: oracle.worstFuture.timeline || "2026: Resource Friction",
      summary: `Inaction or miscalibrated resource allocation on '${decisionClean}' causes operational drag.`
    },
    avatarLetter: {
      salutation,
      bodyParagraphs,
      pivotalAdvice: oracle.recommendation || "Maintain speed of execution and preserve a 3-month capital buffer.",
      signature: "Your Future Self, Year 2035 (Oracle Echo Node)"
    },
    dnaMetrics: {
      risk: oracle.decisionDNA.risk,
      growth: oracle.decisionDNA.growth,
      learning: oracle.decisionDNA.learning,
      time: oracle.decisionDNA.time,
      money: oracle.decisionDNA.money,
      personalSatisfaction: Math.min(100, Math.max(0, Math.round((oracle.decisionDNA.growth + oracle.decisionDNA.learning) / 2))),
      confidence: oracle.decisionDNA.confidence,
      verdict: oracle.recommendation || "STRATEGIC COMMITTAL: High growth asymmetry with manageable downside risk."
    }
  };
}

function adaptServerSimulationToOracle(sim: any): OracleRawOutput {
  return {
    bestFuture: {
      title: sim.bestFuture?.title || "Upside Scenario",
      timeline: sim.bestFuture?.turningPoint || "2026 - 2035",
      probability: sim.bestFuture?.probability || 85,
      advantages: sim.bestFuture?.advantages || [],
      risks: sim.bestFuture?.risks || []
    },
    mostLikelyFuture: {
      title: sim.mostLikelyFuture?.title || "Base Case Scenario",
      timeline: sim.mostLikelyFuture?.turningPoint || "2026 - 2035",
      probability: sim.mostLikelyFuture?.probability || 65,
      advantages: sim.mostLikelyFuture?.advantages || [],
      risks: sim.mostLikelyFuture?.risks || []
    },
    worstFuture: {
      title: sim.worstFuture?.title || "Downside Stress Scenario",
      timeline: sim.worstFuture?.turningPoint || "2026 - 2035",
      probability: sim.worstFuture?.probability || 15,
      advantages: sim.worstFuture?.advantages || [],
      risks: sim.worstFuture?.risks || []
    },
    decisionDNA: {
      risk: sim.dnaMetrics?.risk || 60,
      growth: sim.dnaMetrics?.growth || 85,
      learning: sim.dnaMetrics?.learning || 90,
      money: sim.dnaMetrics?.money || 75,
      time: sim.dnaMetrics?.time || 70,
      confidence: sim.dnaMetrics?.confidence || 88
    },
    butterflyEffect: [
      "Month 3: Velocity attracts key strategic partners",
      "Year 1: Product-market fit milestone reached",
      "Year 3: Compounding advantage established",
      "Year 6: Category leadership unlocked",
      "Year 9: Full sovereignty achieved"
    ],
    futureSelfLetter: sim.avatarLetter?.bodyParagraphs?.join("\n\n") || "Greetings from 2035. Trust the momentum you build today.",
    recommendation: sim.dnaMetrics?.verdict || "Execute with high velocity while maintaining downside protection."
  };
}

/**
 * Graceful Fallback Output when network/API key is unavailable
 */
function getGracefulFallback(goal: string, decision: string): OracleRawOutput {
  return {
    bestFuture: {
      title: `Upside Expansion: ${goal}`,
      timeline: "2026 - 2035",
      probability: 88,
      advantages: [
        `Asymmetrical compound trajectory toward ${goal}`,
        `Sovereignty over resource allocation and timeline`,
        `Network effect attracting high-value partners and capital`,
        `Unlocks key competitive moat by Q4 2027`
      ],
      risks: [
        "Initial capital burn during early acceleration phase",
        "Higher operational cadence required in year 1"
      ]
    },
    mostLikelyFuture: {
      title: `Equilibrium Path: Steady ${goal} Progress`,
      timeline: "2026 - 2035",
      probability: 64,
      advantages: [
        "Predictable milestone attainment with controlled risk",
        "Sustainable resource utilization and low burn rate",
        "Solid fundamental skill acquisition"
      ],
      risks: [
        "Slower market penetration compared to aggressive rivals",
        "Mid-stage execution fatigue"
      ]
    },
    worstFuture: {
      title: `Resource Friction & Stagnation`,
      timeline: "2026 - 2035",
      probability: 18,
      advantages: [
        "Immediate operational risk lessons",
        "Preserves core fallback assets"
      ],
      risks: [
        "Misallocation of primary deadline window",
        "Diminished momentum if resources deplete early",
        "Market sentiment shift"
      ]
    },
    decisionDNA: {
      risk: 62,
      growth: 90,
      learning: 85,
      money: 78,
      time: 72,
      confidence: 88
    },
    butterflyEffect: [
      "Month 3: Early execution momentum generates initial traction",
      "Year 1: Systemic workflow optimization completes",
      "Year 3: Compound advantage yields sustainable revenue",
      "Year 6: Strategic position solidified across market sector",
      "Year 9: Complete creative autonomy and operational sovereignty"
    ],
    futureSelfLetter: `Greetings from August 2035.\n\nI am writing to you from 9 years in your future. Looking back to 2026, I remember standing where you are right now, weighing '${decision}' for '${goal}'.\n\nThe leap felt significant, but every calculated risk you took became our greatest competitive advantage. Trust the data, but execute with unrelenting velocity.`,
    recommendation: `OPTIMAL COMMITTAL: High growth asymmetry with manageable downside risk. Focus on high-velocity execution in the first 90 days.`
  };
}
