/** Evidence Ledger dossier hero: presentation-only title treatment for the existing decision context. */
import React from "react";
import { DecisionCategory, TimeHorizon } from "../../../types/v2";

interface OracleDecisionHeroProps { decisionStatement: string; desiredOutcome?: string; timeHorizon?: TimeHorizon | string; category?: DecisionCategory | string; currentSituation?: string; }
const CATEGORY_LABELS: Record<string, string> = { CAREER_TRANSITION: "Career Transition", BUSINESS_STARTUP: "Business & Venture", CAPITAL_ALLOCATION: "Capital Allocation", RELOCATION_GEO: "Relocation & Geography", HIGHER_EDUCATION: "Education & Development", PARTNERSHIP_COLLAB: "Partnership & Collaboration", PRODUCT_STRATEGY: "Product & Strategy", PERSONAL_LIFESTYLE: "Lifestyle & Personal", STRATEGIC_OTHER: "Strategic Decision" };
const HORIZON_LABELS: Record<string, string> = { LESS_THAN_6_MONTHS: "< 6 Months", "6_TO_12_MONTHS": "6 – 12 Months", "1_TO_3_YEARS": "1 – 3 Years", "3_TO_5_YEARS": "3 – 5 Years", "5_TO_10_YEARS": "5 – 10 Years", "10_PLUS_YEARS": "10+ Years" };

export const OracleDecisionHero: React.FC<OracleDecisionHeroProps> = ({ decisionStatement, desiredOutcome, timeHorizon, category, currentSituation }) => {
  const categoryLabel = category ? CATEGORY_LABELS[category] || category.replace(/_/g, " ") : null;
  const horizonLabel = timeHorizon ? HORIZON_LABELS[timeHorizon] || timeHorizon.replace(/_/g, " ") : null;
  return <section className="grid gap-8 border-b border-[var(--oracle-border-strong)] pb-12 lg:grid-cols-[minmax(0,1fr)_260px] lg:gap-16"><div><div className="mb-5 flex flex-wrap items-center gap-x-3 gap-y-2"><span className="oracle-kicker">01 / Decision dossier</span>{categoryLabel && <span className="border-l border-[var(--oracle-border-strong)] pl-3 text-[11px] font-bold text-[var(--oracle-text-secondary)]">{categoryLabel}</span>}{horizonLabel && <span className="border-l border-[var(--oracle-border-strong)] pl-3 text-[11px] font-bold text-[var(--oracle-text-secondary)]">Horizon: {horizonLabel}</span>}</div><h1 className="oracle-display max-w-[17ch] text-4xl leading-[1.02] text-[var(--oracle-text-primary)] sm:text-5xl lg:text-6xl">{decisionStatement || "Strategic Commitment Analysis"}</h1>{desiredOutcome && <div className="mt-7 max-w-2xl border-l-2 border-[var(--oracle-action)] pl-4"><span className="oracle-technical text-[var(--oracle-text-muted)]">STATED OUTCOME</span><p className="mt-2 text-base leading-7 text-[var(--oracle-text-secondary)]">{desiredOutcome}</p></div>}</div><aside className="border-l border-[var(--oracle-border)] pl-5"><span className="oracle-technical text-[var(--oracle-text-muted)]">DECISION CONTEXT</span><p className="mt-3 text-xs leading-6 text-[var(--oracle-text-secondary)]">{currentSituation || "The stated decision context is reflected in the inputs examined by this dossier."}</p><p className="mt-6 border-t border-[var(--oracle-border)] pt-4 oracle-technical text-[var(--oracle-provenance)]">DETERMINISTIC ANALYSIS RECORD</p></aside></section>;
};
