/** Evidence Ledger contextual explanation: preserves the optional AI boundary and unavailable state exactly. */
import React from "react";
import { AlertCircle, Compass, Sparkles } from "lucide-react";
import { V2NarrativeExplanation } from "../../../types/v2";

interface OracleExplanationSectionProps { explanation?: V2NarrativeExplanation | null; explanationStatus?: "AVAILABLE" | "UNAVAILABLE"; }

export const OracleExplanationSection: React.FC<OracleExplanationSectionProps> = ({ explanation, explanationStatus }) => {
  if (explanationStatus === "UNAVAILABLE" || !explanation) return <section className="border-l-2 border-[var(--oracle-border-strong)] bg-[var(--oracle-surface)] px-5 py-5"><div className="flex items-start gap-3"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0 text-[var(--oracle-text-muted)]" /><div><p className="oracle-kicker !text-[var(--oracle-text-muted)]">03 / Why the signal exists</p><h3 className="mt-2 text-sm font-extrabold text-[var(--oracle-text-primary)]">Explanation Unavailable</h3><p className="mt-1 text-xs leading-5 text-[var(--oracle-text-secondary)]">AI contextual synthesis is currently unavailable. Deterministic decision analysis remains complete, verified, and unaffected.</p></div></div></section>;
  const narratives = [["Financial Exposure", explanation.dimensionExplanations.financialExposure], ["Reversibility", explanation.dimensionExplanations.reversibility], ["Resource Fit", explanation.dimensionExplanations.resourceFit], ["Opportunity Cost", explanation.dimensionExplanations.opportunityCost]];
  return <section className="grid gap-8 border-t border-[var(--oracle-border-strong)] pt-9 lg:grid-cols-[230px_1fr]"><div><p className="oracle-kicker">03 / WHY THE SIGNAL EXISTS</p><h2 className="oracle-display mt-3 text-4xl leading-[1.04]">Contextual synthesis.</h2><p className="mt-4 text-xs leading-5 text-[var(--oracle-text-secondary)]">AI-generated contextual explanation based on the deterministic server analysis.</p><p className="mt-5 border-l-2 border-[var(--oracle-estimated)] bg-[var(--oracle-estimated-bg)] px-3 py-2 text-[10px] leading-4 text-[var(--oracle-estimated)]">OPTIONAL CONTEXT — it does not alter deterministic classifications or calculations.</p></div><div><div className="border-l-2 border-[var(--oracle-action)] bg-[var(--oracle-surface)] px-5 py-5"><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-[var(--oracle-action)]" /><span className="oracle-technical text-[var(--oracle-action)]">CONTEXTUAL SYNTHESIS &amp; CORE TRADE-OFFS</span></div><h3 className="mt-4 text-lg font-extrabold text-[var(--oracle-text-primary)]">{explanation.executiveSummary.headline}</h3><p className="mt-3 text-sm leading-6 text-[var(--oracle-text-secondary)]">{explanation.executiveSummary.coreTradeoffSummary}</p><p className="mt-4 oracle-technical text-[var(--oracle-action)]">EPISTEMIC STANCE: {explanation.executiveSummary.epistemicStatusSummary}</p></div><div className="mt-5 divide-y divide-[var(--oracle-border)] border-y border-[var(--oracle-border)]">{narratives.map(([label, body], index) => <article key={label} className="grid gap-2 py-4 sm:grid-cols-[32px_180px_1fr]"><span className="oracle-technical text-[var(--oracle-text-muted)]">0{index + 1}</span><h4 className="text-xs font-extrabold text-[var(--oracle-text-primary)]">{label}</h4><p className="text-xs leading-5 text-[var(--oracle-text-secondary)]">{body}</p></article>)}</div>{explanation.dataGapsAndNextSteps?.recommendedInformationToCollect?.length ? <div className="mt-5 border-l-2 border-[var(--oracle-provenance)] bg-[var(--oracle-provenance-bg)] px-4 py-4"><div className="flex items-center gap-2 text-xs font-extrabold text-[var(--oracle-provenance)]"><Compass className="h-4 w-4" />Recommended Verification Steps:</div><ul className="mt-3 list-disc space-y-1 pl-4 text-xs leading-5 text-[var(--oracle-text-secondary)]">{explanation.dataGapsAndNextSteps.recommendedInformationToCollect.map((item, index) => <li key={index}>{item}</li>)}</ul></div> : null}</div></section>;
};
