/** Evidence Ledger unknown-variable index: preserves model-supplied unknown and not-provided counts. */
import React from "react";
import { HelpCircle } from "lucide-react";

interface OracleUnknownVariablesSectionProps { criticalUnknownVariables: string[]; unknownCount: number; notProvidedCount: number; }
const VARIABLE_LABELS: Record<string, string> = { currentMonthlyIncome: "Current baseline monthly income", recurringMonthlyExpenses: "Recurring monthly living/operating expenses", availableLiquidCapital: "Available liquid capital reserves", existingFinancialObligations: "Existing financial obligations / debt commitments", expectedIncomeChangeMonthly: "Expected post-decision monthly income delta", requiredUpfrontCapital: "Required upfront capital outlay", availableWeeklyHours: "Dedicated weekly time budget", experienceYears: "Years of domain experience", unwindingTimeMonths: "Estimated unwinding / reversal timeline", sunkCostsAmount: "Immediate non-recoverable sunk outlay", estimatedSwitchingEffort: "Switching friction level" };

export const OracleUnknownVariablesSection: React.FC<OracleUnknownVariablesSectionProps> = ({ criticalUnknownVariables, unknownCount, notProvidedCount }) => {
  const hasUnknowns = criticalUnknownVariables?.length || unknownCount > 0 || notProvidedCount > 0;
  if (!hasUnknowns) return null;
  return <section className="grid gap-7 border-y border-[var(--oracle-border-strong)] py-7 lg:grid-cols-[230px_1fr]"><div><p className="oracle-kicker !text-[var(--oracle-unknown)]">What remains unestablished</p><h3 className="oracle-display mt-3 text-3xl leading-[1.04]">Unknown variables.</h3><p className="mt-3 text-xs leading-5 text-[var(--oracle-text-secondary)]">They are preserved in the record rather than silently transformed into zeros or empty certainty.</p></div><div>{criticalUnknownVariables?.length ? <ol className="divide-y divide-[var(--oracle-border)] border-y border-[var(--oracle-border)]">{criticalUnknownVariables.map((name, index) => <li key={`${name}-${index}`} className="grid gap-2 py-4 sm:grid-cols-[32px_1fr_auto]"><span className="oracle-technical text-[var(--oracle-unknown)]">0{index + 1}</span><div><span className="text-xs font-extrabold text-[var(--oracle-text-primary)]">{VARIABLE_LABELS[name] || name}</span><p className="mt-1 text-[11px] leading-5 text-[var(--oracle-text-secondary)]">Unspecified during intake — carried through the deterministic model as an explicit uncertainty boundary.</p></div><span className="inline-flex h-fit items-center gap-1 text-[10px] font-extrabold text-[var(--oracle-unknown)]"><HelpCircle className="h-3.5 w-3.5" />UNKNOWN</span></li>)}</ol> : <div className="border-l-2 border-[var(--oracle-unknown)] bg-[var(--oracle-unknown-bg)] px-4 py-4 text-xs leading-5 text-[var(--oracle-unknown)]"><strong>{unknownCount} marked Unknown; {notProvidedCount} marked Not Provided.</strong> These values remain distinct and are not converted to zero.</div>}</div></section>;
};
