/** Evidence Ledger evidence coverage: presents existing coverage and evidence measurements without altering states. */
import React from "react";
import { Database, FileText, ShieldCheck } from "lucide-react";
import { DataCoverageSummary, EvidenceConfidenceClassification, EvidenceConfidenceMeasurements } from "../../../types/v2";
import { OracleStatus, OracleStatusType } from "../OracleStatus";

interface OracleDataEvidenceSectionProps { dataCoverage: DataCoverageSummary; evidenceClassification: EvidenceConfidenceClassification; evidenceMeasurements: EvidenceConfidenceMeasurements; overallSufficiencyStatus?: string; }
const evidenceType = (classification: string): OracleStatusType => classification === "STRONGLY_EVIDENCED" ? "favorable" : classification === "MODERATELY_EVIDENCED" ? "baseline" : ["ASSUMPTION_HEAVY", "UNVERIFIED_ASSERTION"].includes(classification) ? "attention" : "unknown";

export const OracleDataEvidenceSection: React.FC<OracleDataEvidenceSectionProps> = ({ dataCoverage, evidenceClassification, evidenceMeasurements, overallSufficiencyStatus }) => {
  const coveragePercentage = Math.round(dataCoverage.coverageRatio * 100);
  const coverageRows = [["Required variables", dataCoverage.requiredVariableCount, "text-[var(--oracle-text-primary)]"], ["Known", dataCoverage.knownVariableCount, "text-[var(--oracle-provenance)]"], ["Unknown", dataCoverage.unknownVariableCount, "text-[var(--oracle-unknown)]"], ["Not provided", dataCoverage.notProvidedVariableCount, "text-[var(--oracle-text-secondary)]"]] as const;
  const evidenceRows = [["Verified external", evidenceMeasurements.verifiedExternalCount || 0], ["User statements", evidenceMeasurements.userProvidedCount || 0], ["Active assumptions", evidenceMeasurements.totalAssumptionCount || 0], ["Heuristic assumptions", evidenceMeasurements.heuristicAssumptionCount || 0]] as const;
  return <section className="space-y-7"><div className="flex gap-3 border-l-2 border-[var(--oracle-action)] bg-[var(--oracle-action-subtle)] px-4 py-4 text-xs leading-5 text-[var(--oracle-text-secondary)]"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-[var(--oracle-action)]" /><div><span className="block text-[11px] font-extrabold tracking-[0.06em] text-[var(--oracle-text-primary)]">EPISTEMIC BOUNDARY NOTICE</span><p className="mt-1">Evidence confidence reflects evidence quality. It does not represent the probability that an ORACLE conclusion is correct.</p></div></div><div className="grid gap-10 lg:grid-cols-2"><article className="border-y border-[var(--oracle-border-strong)] py-5"><header className="flex items-start justify-between gap-4 border-b border-[var(--oracle-border)] pb-4"><div className="flex gap-2"><Database className="mt-0.5 h-4 w-4 text-[var(--oracle-action)]" /><div><h3 className="text-sm font-extrabold text-[var(--oracle-text-primary)]">Data Coverage</h3><p className="mt-1 text-[11px] text-[var(--oracle-text-secondary)]">Variable completeness from user intake.</p></div></div><span className="oracle-technical text-[var(--oracle-action)]">{coveragePercentage}% COVERAGE</span></header><div className="mt-5 divide-y divide-[var(--oracle-border)] border-y border-[var(--oracle-border)]">{coverageRows.map(([label, value, tone]) => <div key={label} className="flex items-center justify-between py-3"><span className="text-xs text-[var(--oracle-text-secondary)]">{label}</span><span className={`font-mono text-sm font-bold ${tone}`}>{value}</span></div>)}</div>{overallSufficiencyStatus && <p className="mt-4 oracle-technical text-[var(--oracle-text-muted)]">SUFFICIENCY PROFILE: {overallSufficiencyStatus.replace(/_/g, " ")}</p>}</article><article className="border-y border-[var(--oracle-border-strong)] py-5"><header className="flex items-start justify-between gap-4 border-b border-[var(--oracle-border)] pb-4"><div className="flex gap-2"><FileText className="mt-0.5 h-4 w-4 text-[var(--oracle-provenance)]" /><div><h3 className="text-sm font-extrabold text-[var(--oracle-text-primary)]">Evidence Quality</h3><p className="mt-1 text-[11px] text-[var(--oracle-text-secondary)]">Verification depth and assumption weight.</p></div></div><OracleStatus type={evidenceType(evidenceClassification)} label={evidenceClassification.replace(/_/g, " ")} size="sm" /></header><div className="mt-5 divide-y divide-[var(--oracle-border)] border-y border-[var(--oracle-border)]">{evidenceRows.map(([label, value]) => <div key={label} className="flex items-center justify-between py-3"><span className="text-xs text-[var(--oracle-text-secondary)]">{label}</span><span className="font-mono text-sm font-bold text-[var(--oracle-text-primary)]">{value}</span></div>)}</div><p className="mt-4 oracle-technical text-[var(--oracle-text-muted)]">TOTAL GROUNDED EVIDENCE: {evidenceMeasurements.totalEvidenceCount || 0} RECORDED ITEMS</p></article></div></section>;
};
