/** Evidence Ledger signal summary: renders only existing deterministic DNA classifications and directions. */
import React from "react";
import { DecisionDNAV2Result } from "../../../types/v2";
import { OracleStatus, OracleStatusType } from "../OracleStatus";

interface OracleSignalSummaryProps { dna: DecisionDNAV2Result; sufficiencyStatus?: string; }
const FINANCIAL_LABELS: Record<string, { label: string; type: OracleStatusType }> = { MINIMAL_EXPOSURE: { label: "Minimal Exposure", type: "favorable" }, MODERATE_EXPOSURE: { label: "Moderate Exposure", type: "baseline" }, SIGNIFICANT_EXPOSURE: { label: "Significant Exposure", type: "attention" }, ACUTE_EXPOSURE: { label: "Acute Exposure", type: "stress" }, INSUFFICIENT_DATA: { label: "Insufficient Data", type: "unknown" } };
const REVERSIBILITY_LABELS: Record<string, { label: string; type: OracleStatusType }> = { HIGHLY_REVERSIBLE: { label: "Highly Reversible", type: "favorable" }, MODERATELY_REVERSIBLE: { label: "Moderately Reversible", type: "baseline" }, LOW_REVERSIBILITY: { label: "Low Reversibility", type: "attention" }, SUBSTANTIALLY_IRREVERSIBLE: { label: "Substantially Irreversible", type: "stress" }, INSUFFICIENT_DATA: { label: "Insufficient Data", type: "unknown" } };
const RESOURCE_FIT_LABELS: Record<string, { label: string; type: OracleStatusType }> = { STRONG_FIT: { label: "Strong Resource Fit", type: "favorable" }, MODERATE_FIT: { label: "Moderate Fit", type: "baseline" }, RESOURCE_CONSTRAINED: { label: "Resource Constrained", type: "attention" }, INSUFFICIENT_DATA: { label: "Insufficient Data", type: "unknown" } };
const OPPORTUNITY_COST_LABELS: Record<string, { label: string; type: OracleStatusType }> = { LOW_FOREGONE_VALUE: { label: "Low Foregone Value", type: "favorable" }, MODERATE_FOREGONE_VALUE: { label: "Moderate Foregone Value", type: "baseline" }, HIGH_FOREGONE_VALUE: { label: "High Foregone Value", type: "attention" }, INSUFFICIENT_DATA: { label: "Insufficient Data", type: "unknown" } };
const UPSIDE_POTENTIAL_LABELS: Record<string, { label: string; type: OracleStatusType }> = { DEFINED_ASYMMETRIC_UPSIDE: { label: "Defined Asymmetric Upside", type: "favorable" }, DEFINED_LINEAR_UPSIDE: { label: "Defined Linear Upside", type: "baseline" }, QUALITATIVE_TARGET_STATED: { label: "Qualitative Target Stated", type: "baseline" }, INSUFFICIENT_DATA: { label: "Insufficient Data", type: "unknown" } };
const EVIDENCE_CONFIDENCE_LABELS: Record<string, { label: string; type: OracleStatusType }> = { STRONGLY_EVIDENCED: { label: "Strongly Evidenced", type: "favorable" }, MODERATELY_EVIDENCED: { label: "Moderately Evidenced", type: "baseline" }, ASSUMPTION_HEAVY: { label: "Assumption Heavy", type: "attention" }, UNVERIFIED_ASSERTION: { label: "Unverified Assertions", type: "attention" }, INSUFFICIENT_DATA: { label: "Insufficient Data", type: "unknown" } };

export const OracleSignalSummary: React.FC<OracleSignalSummaryProps> = ({ dna, sufficiencyStatus }) => {
  const fallback = (classification: string) => ({ label: classification.replace(/_/g, " "), type: "baseline" as OracleStatusType });
  const signals = [
    ["Financial Exposure", FINANCIAL_LABELS[dna.financialExposure.classification] || fallback(dna.financialExposure.classification), dna.financialExposure.semanticDirection],
    ["Reversibility", REVERSIBILITY_LABELS[dna.reversibility.classification] || fallback(dna.reversibility.classification), dna.reversibility.semanticDirection],
    ["Resource Fit", RESOURCE_FIT_LABELS[dna.resourceFit.classification] || fallback(dna.resourceFit.classification), dna.resourceFit.semanticDirection],
    ["Opportunity Cost", OPPORTUNITY_COST_LABELS[dna.opportunityCost.classification] || fallback(dna.opportunityCost.classification), dna.opportunityCost.semanticDirection],
    ["Upside Potential", UPSIDE_POTENTIAL_LABELS[dna.upsidePotential.classification] || fallback(dna.upsidePotential.classification), dna.upsidePotential.semanticDirection],
    ["Evidence Quality", EVIDENCE_CONFIDENCE_LABELS[dna.evidenceConfidence.classification] || fallback(dna.evidenceConfidence.classification), dna.evidenceConfidence.semanticDirection],
  ] as const;
  return <section className="grid gap-8 border-y border-[var(--oracle-border-strong)] bg-[var(--oracle-surface)] px-5 py-8 sm:px-7 lg:grid-cols-[230px_1fr]"><div><p className="oracle-kicker">02 / The Signal</p><h2 className="oracle-display mt-3 text-4xl leading-[1.04]">The structural reading.</h2><p className="mt-4 text-xs leading-5 text-[var(--oracle-text-secondary)]">Six deterministic classifications. Each describes a distinct feature of the decision—not a composite score.</p>{sufficiencyStatus && <p className="mt-5 oracle-technical text-[var(--oracle-text-muted)]">SUFFICIENCY: {sufficiencyStatus.replace(/_/g, " ")}</p>}</div><div className="divide-y divide-[var(--oracle-border)] border-y border-[var(--oracle-border)]">{signals.map(([label, status, summary], index) => <article key={label} className="grid gap-3 py-4 sm:grid-cols-[34px_minmax(145px,.6fr)_minmax(0,1fr)_auto] sm:items-center"><span className="oracle-technical text-[var(--oracle-action)]">0{index + 1}</span><h3 className="text-sm font-extrabold text-[var(--oracle-text-primary)]">{label}</h3><p className="text-xs leading-5 text-[var(--oracle-text-secondary)]">{summary}</p><OracleStatus type={status.type} label={status.label} size="sm" /></article>)}</div></section>;
};
