import React, { useMemo, useState } from "react";
import { ArrowDownRight, ArrowUpRight, CheckCircle2, ChevronRight, CircleAlert, FileCheck2, Hash, Layers3, LockKeyhole, Scale, Shield, Sparkles, Target, Timer, TrendingDown, TrendingUp } from "lucide-react";
import { motion } from "motion/react";
import { CanonicalScenarioType, V2DecisionPayload, ValueState } from "../../../types/v2";
import { DossierData, selectCausalGraphLayout, selectDossierDimensions, selectDossierIdentity, selectDossierScenarios, selectEvidenceLedger, selectMilestoneRail } from "../../../presentation/oracleDossierSelectors";
import { OracleBoundaryMarker, OracleCausalGraph, OracleEvidenceBadge, OracleInstrumentDisclosure, OracleMetricSignal, OracleProvenanceBadge, OracleRunwayGauge, OracleStateBadge, OracleTimelineRail, OracleTrajectoryRail } from "../OracleInstrumentPrimitives";
import { OracleDataEvidenceSection } from "./OracleDataEvidenceSection";
import { OracleDecisionCore } from "./OracleDecisionCore";
import { OracleDecisionDnaSection } from "./OracleDecisionDnaSection";
import { OracleSignalSummary } from "./OracleSignalSummary";
import { OracleTemporalTimeline } from "./OracleTemporalTimeline";
import { OracleTrajectoryExplorer } from "./OracleTrajectoryExplorer";
import { OracleUnknownVariablesSection } from "./OracleUnknownVariablesSection";
import { OracleExplanationSection } from "./OracleExplanationSection";
import { OracleWarningsSection } from "./OracleWarningsSection";

export interface OracleDecisionDossierProps {
  data: DossierData;
  payload: V2DecisionPayload;
  decisionStatement: string;
  desiredOutcome?: string;
  timeHorizon?: string;
  category?: string;
  currentSituation?: string;
  onInspectProvenance: (dimensionName: string, hash?: string) => void;
  onSwitchView: (view: "what-if" | "evidence" | "future-self") => void;
  selectedScenarioType: CanonicalScenarioType;
  onSelectScenarioType: (type: CanonicalScenarioType) => void;
  selectedMilestoneId: string | null;
  onSelectMilestone: (milestoneId: string | null) => void;
}

const sectionItems = [
  ["dossier-identification", "01", "Identification"],
  ["dossier-executive", "02", "Executive reading"],
  ["dossier-structural", "03", "Structural signal"],
  ["dossier-dna", "04", "Decision DNA"],
  ["dossier-financial", "05", "Financial reality"],
  ["dossier-capacity", "06", "Execution capacity"],
  ["dossier-reversibility", "07", "Reversibility"],
  ["dossier-opportunity", "08", "Opportunity cost"],
  ["dossier-upside", "09", "Upside potential"],
  ["dossier-evidence", "10", "Evidence & assumptions"],
  ["dossier-trajectories", "11", "Conditional trajectories"],
  ["dossier-temporal", "12", "Temporal milestones"],
  ["dossier-provenance", "13", "Calculation record"],
  ["dossier-final", "14", "Final reading"],
] as const;

const humanize = (value?: string) => value ? value.replace(/_/g, " ") : "Not provided";
const stateFor = (value: unknown, state?: ValueState): ValueState => state || (value === undefined || value === null ? "INSUFFICIENT_DATA" : "CALCULATED");
const formatMoney = (value: number | undefined, currency?: string) => value === undefined ? "Not provided" : `${currency ? `${currency} ` : ""}${value.toLocaleString()}`;
const formatNumber = (value: number | undefined, suffix = "") => value === undefined ? "Not provided" : `${value.toLocaleString()}${suffix}`;
const formatDate = (value: string | undefined) => value ? new Date(value).toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" }) : "Evaluation timestamp unavailable";
const evidenceState = (verificationStatus: string): "KNOWN" | "ASSUMED" | "UNKNOWN" => verificationStatus === "VERIFIED_EXTERNAL" || verificationStatus === "MULTI_SOURCE_VERIFIED" || verificationStatus === "USER_PROVIDED" ? "KNOWN" : verificationStatus === "UNVERIFIED" ? "ASSUMED" : "UNKNOWN";

const SectionHeader: React.FC<{ number: string; eyebrow: string; title: string; description?: string }> = ({ number, eyebrow, title, description }) => (
  <header className="oracle-dossier-section-header">
    <div className="oracle-dossier-index-mark"><span>{number}</span><span className="oracle-dossier-index-line" aria-hidden="true" /></div>
    <div><p className="oracle-kicker">{eyebrow}</p><h2 className="oracle-display mt-2 text-3xl leading-[1.04] sm:text-4xl">{title}</h2>{description && <p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--oracle-text-secondary)]">{description}</p>}</div>
  </header>
);

export const OracleDecisionDossier: React.FC<OracleDecisionDossierProps> = ({ data, payload, decisionStatement, desiredOutcome, timeHorizon, category, currentSituation, onInspectProvenance, onSwitchView, selectedScenarioType, onSelectScenarioType, selectedMilestoneId, onSelectMilestone }) => {
  const [activeSection, setActiveSection] = useState("dossier-identification");
  const currency = payload?.financial?.currency;
  const dimensions = useMemo(() => selectDossierDimensions(data.decisionDNA, currency), [data.decisionDNA, currency]);
  const scenarioViews = useMemo(() => selectDossierScenarios(data.scenarios), [data.scenarios]);
  const activeScenario = scenarioViews.find((scenario) => scenario.type === selectedScenarioType) || scenarioViews[0];
  const identity = selectDossierIdentity(decisionStatement, desiredOutcome, timeHorizon, category, currentSituation);
  const ledger = selectEvidenceLedger(payload);
  const financial = data.decisionDNA.financialExposure.measurements;
  const resources = data.decisionDNA.resourceFit.measurements;
  const reversibility = data.decisionDNA.reversibility.measurements;
  const opportunity = data.decisionDNA.opportunityCost.measurements;
  const upside = data.decisionDNA.upsidePotential.measurements;
  const coverage = data.decisionDNA.dataCoverage;
  const baseGraph = selectCausalGraphLayout(data.scenarios.baseCase);
  const milestonePoints = selectMilestoneRail(activeScenario.contract, selectedMilestoneId);
  const sufficiencyState: ValueState = data.dataSufficiency?.overallStatus === "FULLY_DETERMINED" ? "CALCULATED" : data.dataSufficiency?.overallStatus === "UNDER_DETERMINED" ? "INSUFFICIENT_DATA" : "UNKNOWN";

  const goToSection = (id: string) => {
    setActiveSection(id);
    document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" });
  };

  return (
    <div className="oracle-dossier-reading">
      <aside className="oracle-dossier-index-rail" aria-label="Decision dossier sections">
        <div className="oracle-dossier-index-rail-inner">
          <p className="oracle-kicker">Decision dossier</p>
          <p className="mt-2 text-xs leading-5 text-[var(--oracle-text-secondary)]">A continuous reading of structure, conditions, evidence, and boundaries.</p>
          <nav className="mt-7 space-y-1">
            {sectionItems.map(([id, number, label]) => <button key={id} type="button" onClick={() => goToSection(id)} className={`oracle-dossier-index-link ${activeSection === id ? "is-active" : ""}`}><span>{number}</span><span>{label}</span><ChevronRight className="ml-auto h-3.5 w-3.5" aria-hidden="true" /></button>)}
          </nav>
          <OracleProvenanceBadge className="mt-7" methodologyVersion={data.auditTrail.dnaMethodologyVersion} />
        </div>
      </aside>

      <main className="min-w-0 space-y-16">
        <section id="dossier-identification" className="oracle-dossier-opening scroll-mt-28">
          <div className="flex flex-wrap items-center gap-2"><span className="oracle-kicker">01 / Decision identification</span><OracleStateBadge state={sufficiencyState} label={humanize(data.dataSufficiency?.overallStatus)} compact /><OracleProvenanceBadge methodologyVersion={data.auditTrail.dnaMethodologyVersion} /></div>
          <div className="mt-7 grid gap-10 xl:grid-cols-[minmax(0,1fr)_250px] xl:gap-16">
            <div><h1 className="oracle-display max-w-[15ch] text-5xl leading-[.98] text-[var(--oracle-text-primary)] sm:text-6xl lg:text-7xl">{identity.decisionStatement || "Strategic commitment analysis"}</h1>{identity.desiredOutcome && <div className="mt-8 max-w-2xl border-l-2 border-[var(--oracle-action)] pl-5"><span className="oracle-technical text-[var(--oracle-text-muted)]">STATED OUTCOME</span><p className="mt-2 text-lg leading-7 text-[var(--oracle-text-secondary)]">{identity.desiredOutcome}</p></div>}</div>
            <aside className="border-l border-[var(--oracle-border)] pl-5"><p className="oracle-kicker">Record context</p><dl className="mt-5 space-y-4 text-xs"><div><dt className="oracle-technical text-[var(--oracle-text-muted)]">DECISION DOMAIN</dt><dd className="mt-1 font-bold text-[var(--oracle-text-primary)]">{identity.category || "Not provided"}</dd></div><div><dt className="oracle-technical text-[var(--oracle-text-muted)]">TIME HORIZON</dt><dd className="mt-1 font-bold text-[var(--oracle-text-primary)]">{identity.timeHorizon || "Not provided"}</dd></div><div><dt className="oracle-technical text-[var(--oracle-text-muted)]">ANALYSED</dt><dd className="mt-1 font-bold text-[var(--oracle-text-primary)]">{formatDate(data.auditTrail.serverEvaluatedAt)}</dd></div></dl><p className="mt-7 border-t border-[var(--oracle-border)] pt-4 oracle-technical text-[var(--oracle-provenance)]">SERVER-AUTHORITATIVE RECORD</p></aside>
          </div>
        </section>

        <section id="dossier-executive" className="scroll-mt-28"><SectionHeader number="02" eyebrow="Executive reading" title="See the structural situation before reading the detail." description="These are six independent deterministic classifications. ORACLE does not collapse them into an overall score." /><div className="mt-7"><OracleSignalSummary dna={data.decisionDNA} sufficiencyStatus={data.dataSufficiency?.overallStatus} /></div><div className="mt-7"><OracleWarningsSection warnings={data.warnings} /></div><div className="mt-7"><OracleExplanationSection explanation={data.explanation} explanationStatus={data.explanationStatus} /></div></section>

        <section id="dossier-structural" className="scroll-mt-28"><SectionHeader number="03" eyebrow="Decision Core" title="Examine what this decision is made of." description="The spatial layer makes the six existing Decision DNA dimensions easier to orient around the decision. It introduces no new scores, relationships, or conclusions." /><div className="mt-7"><OracleDecisionCore decisionStatement={decisionStatement} dimensions={dimensions} onInspectProvenance={onInspectProvenance} /></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><OracleBoundaryMarker label="Active constraints" value={formatNumber(data.scenarios.baseCase.activeConstraints.length)} description="Retained from the base-case contract." tone="risk" /><OracleBoundaryMarker label="Critical unknowns" value={formatNumber(data.dataSufficiency?.criticalUnknownVariables.length)} description="Kept explicit in the record." tone="unknown" /><OracleBoundaryMarker label="Causal graph" value={baseGraph.nodes.length ? `${baseGraph.nodes.length} nodes / ${baseGraph.edges.length} links` : "Not provided"} description="Existing structure only; no decorative relationships added." tone="provenance" /></div></section>

        <section id="dossier-dna" className="scroll-mt-28"><SectionHeader number="04" eyebrow="Decision DNA" title="Explore the six dimensions of the record." description="Select a dimension to reveal its authoritative measurements, deterministic classification, contributing variables, assumptions, and provenance." /><div className="mt-7"><OracleDecisionDnaSection dna={data.decisionDNA} onInspectProvenance={onInspectProvenance} /></div></section>

        <section id="dossier-financial" className="scroll-mt-28"><SectionHeader number="05" eyebrow="Financial reality" title="Capital is a finite physical resource." description="The dossier turns already-calculated capital, monthly cash, burn, coverage, and runway values into a readable instrument." /><div className="mt-7 grid gap-7 lg:grid-cols-[minmax(0,1fr)_minmax(260px,.8fr)]"><div className="oracle-instrument-surface"><div className="grid gap-4 sm:grid-cols-2"><OracleMetricSignal label="Post-commitment liquid capital" value={formatMoney(financial.postCommitmentLiquidCapital, currency)} state={stateFor(financial.postCommitmentLiquidCapital)} accent="action" detail="Existing deterministic output." /><OracleMetricSignal label="Monthly net cash" value={formatMoney(financial.monthlyNetCashPosition, currency)} state={stateFor(financial.monthlyNetCashPosition)} accent={financial.monthlyNetCashPosition !== undefined && financial.monthlyNetCashPosition < 0 ? "risk" : "provenance"} detail="Existing deterministic output." /><OracleMetricSignal label="Monthly burn" value={formatMoney(financial.monthlyBurn, currency)} state={stateFor(financial.monthlyBurn)} accent="neutral" detail="Existing deterministic output." /><OracleMetricSignal label="Capital coverage" value={financial.capitalCoverage === undefined ? "Not provided" : financial.capitalCoverage.toFixed(2)} state={stateFor(financial.capitalCoverage)} accent="evidence" detail="Ratio supplied by the engine." /></div></div><OracleRunwayGauge label="Runway boundary" value={financial.runwayStatus === "SURPLUS_OR_NON_BURN" ? "Surplus / non-burn" : formatNumber(financial.runwayMonths, " months")} state={stateFor(financial.runwayMonths, financial.runwayStatus === "SURPLUS_OR_NON_BURN" ? "CALCULATED" : undefined)} position={typeof financial.capitalCoverage === "number" ? financial.capitalCoverage * 100 : undefined} detail="The gauge visualizes the existing capital-coverage relationship; it does not infer missing runway." /></div></section>

        <section id="dossier-capacity" className="scroll-mt-28"><SectionHeader number="06" eyebrow="Execution capacity" title="Available capacity is different from ambition." description="Only supplied hours, experience, skills, support, assets, and resource gaps appear here." /><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><OracleMetricSignal label="Available weekly hours" value={formatNumber(resources.availableWeeklyHours, " hrs / week")} state={stateFor(resources.availableWeeklyHours)} accent="action" /><OracleMetricSignal label="Domain experience" value={formatNumber(resources.experienceYears, " years")} state={stateFor(resources.experienceYears)} accent="temporal" /><OracleMetricSignal label="Skills" value={`${resources.relevantSkillsCount} identified`} state="CALCULATED" accent="evidence" /><OracleMetricSignal label="Resource gaps" value={resources.resourceGapsIdentified.length ? `${resources.resourceGapsIdentified.length} identified` : "None identified"} state="CALCULATED" accent={resources.resourceGapsIdentified.length ? "risk" : "provenance"} /></div><div className="mt-5 grid gap-4 lg:grid-cols-3"><OracleBoundaryMarker label="Skills" value={resources.relevantSkills.join(" · ") || "Not provided"} tone="action" /><OracleBoundaryMarker label="Support network" value={resources.supportNetwork.join(" · ") || "Not provided"} tone="provenance" /><OracleBoundaryMarker label="Physical assets" value={resources.physicalAssets.join(" · ") || "Not provided"} tone="evidence" /></div></section>

        <section id="dossier-reversibility" className="scroll-mt-28"><SectionHeader number="07" eyebrow="Reversibility" title="Make the cost of unwinding visible." description="Decision, commitment, unwind, and recovery remain a structural sequence. The values below come directly from the reversibility result." /><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><OracleBoundaryMarker label="Switching effort" value={humanize(reversibility.switchingEffortLevel)} description="Authoritative friction classification." tone="risk" /><OracleBoundaryMarker label="Unwinding time" value={formatNumber(reversibility.unwindingTimeMonths, " months")} description="Existing recorded horizon." tone="temporal" /><OracleBoundaryMarker label="Sunk costs" value={formatMoney(reversibility.sunkCostsAmount, currency)} description="Existing recorded outlay." tone="risk" /><OracleBoundaryMarker label="Material constraints" value={reversibility.dominantMaterialConstraint || "Not provided"} description={`${reversibility.irreversibleCommitmentCount} irreversible / ${reversibility.contractualConstraintCount} contractual`} tone="unknown" /></div><div className="mt-5 oracle-instrument-surface oracle-reversibility-sequence"><div className="oracle-reversibility-step"><span>01</span><strong>DECISION</strong><small>Stated choice</small></div><div className="oracle-reversibility-connector" aria-hidden="true" /><div className="oracle-reversibility-step"><span>02</span><strong>COMMITMENT</strong><small>Recorded friction</small></div><div className="oracle-reversibility-connector" aria-hidden="true" /><div className="oracle-reversibility-step"><span>03</span><strong>UNWIND</strong><small>{formatNumber(reversibility.unwindingTimeMonths, " months")}</small></div><div className="oracle-reversibility-connector" aria-hidden="true" /><div className="oracle-reversibility-step"><span>04</span><strong>RECOVERY</strong><small>Not inferred</small></div></div></section>

        <section id="dossier-opportunity" className="scroll-mt-28"><SectionHeader number="08" eyebrow="Opportunity cost" title="See what the chosen path trades away." description="The dossier compares the chosen path with the alternatives that are already identified, without ranking them." /><div className="mt-7 grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]"><div className="oracle-contrast-panel"><div className="oracle-contrast-panel-heading"><Target className="h-4 w-4" /><span>CHOSEN PATH</span></div><p className="oracle-display mt-4 text-2xl leading-tight">{decisionStatement}</p><p className="mt-4 text-xs leading-5 text-[var(--oracle-text-secondary)]">The path under analysis. Its structural trade-offs remain conditional and auditable.</p></div><div className="oracle-contrast-panel oracle-contrast-panel-muted"><div className="oracle-contrast-panel-heading"><Scale className="h-4 w-4" /><span>ALTERNATIVES ON RECORD</span></div><p className="oracle-display mt-4 text-3xl leading-tight">{opportunity.alternativesConsideredCount}</p><p className="mt-1 text-xs text-[var(--oracle-text-secondary)]">identified alternative{opportunity.alternativesConsideredCount === 1 ? "" : "s"}</p><div className="mt-4 space-y-2 border-t border-[var(--oracle-border)] pt-4"><OracleMetricSignal label="Foregone horizon income" value={formatMoney(opportunity.foregoneIncomeOverHorizon, currency)} state={stateFor(opportunity.foregoneIncomeOverHorizon)} accent="risk" /><OracleMetricSignal label="Foregone benefits" value={`${opportunity.foregoneBenefitsCount} identified`} state="CALCULATED" accent="neutral" /></div></div></div></section>

        <section id="dossier-upside" className="scroll-mt-28"><SectionHeader number="09" eyebrow="Upside potential" title="A stated target is a destination, not a prediction." description="This section separates the user-stated target from calculated outputs and explicit assumptions." /><div className="mt-7 grid gap-5 lg:grid-cols-[minmax(0,1.15fr)_minmax(260px,.85fr)]"><div className="oracle-destination-panel"><div className="flex items-center justify-between gap-4"><div className="oracle-kicker">STATED TARGET</div><OracleStateBadge state="KNOWN" label="User stated" compact /></div><p className="oracle-display mt-5 max-w-[22ch] text-3xl leading-tight">{upside.userStatedTargetOutcome || "Target not provided"}</p><div className="mt-7 grid gap-3 border-t border-[var(--oracle-border)] pt-4 sm:grid-cols-2"><OracleMetricSignal label="Target monthly delta" value={formatMoney(upside.userStatedTargetDifferenceMonthly, currency)} state={stateFor(upside.userStatedTargetDifferenceMonthly)} accent="action" /><OracleMetricSignal label="Horizon" value={humanize(upside.timeHorizon)} state="KNOWN" accent="temporal" /></div></div><div className="space-y-3"><OracleBoundaryMarker label="Calculated result" value={formatMoney(data.scenarios.baseCase.calculations.monthlyNetCashPosition, currency)} description="Existing base-case output, not the stated target." tone="action" /><OracleBoundaryMarker label="Assumptions" value={`${data.scenarios.baseCase.appliedAssumptions.length} applied`} description="Open the scenario detail to inspect them." tone="unknown" /></div></div></section>

        <section id="dossier-evidence" className="scroll-mt-28"><SectionHeader number="10" eyebrow="Evidence & assumptions" title="Known is not assumed, and unknown is not zero." description="The record preserves distinct ledgers for evidence, assumptions, unknown variables, and insufficient data." /><div className="mt-7 grid gap-6 lg:grid-cols-2"><div className="oracle-ledger oracle-ledger-evidence"><div className="oracle-ledger-heading"><FileCheck2 className="h-4 w-4" /><div><p className="oracle-kicker">What I know</p><p className="mt-1 text-xs text-[var(--oracle-text-secondary)]">Evidence and records carried into analysis.</p></div><span className="oracle-technical">{ledger.evidence.length} ITEMS</span></div><div className="mt-5 space-y-3">{ledger.evidence.length ? ledger.evidence.map((item) => <article key={item.id} className="oracle-ledger-row"><div><p className="text-xs font-bold text-[var(--oracle-text-primary)]">{item.description}</p><p className="mt-1 oracle-technical text-[var(--oracle-text-muted)]">{humanize(item.verificationStatus)} · {humanize(item.relevance)}</p></div><OracleEvidenceBadge state={evidenceState(item.verificationStatus)} source={humanize(item.sourceType)} /></article>) : <p className="text-xs text-[var(--oracle-text-muted)]">No evidence items provided.</p>}</div></div><div className="oracle-ledger oracle-ledger-assumption"><div className="oracle-ledger-heading"><Sparkles className="h-4 w-4" /><div><p className="oracle-kicker">What I assume</p><p className="mt-1 text-xs text-[var(--oracle-text-secondary)]">Working hypotheses remain separate from evidence.</p></div><span className="oracle-technical">{ledger.assumptions.length} ITEMS</span></div><div className="mt-5 space-y-3">{ledger.assumptions.length ? ledger.assumptions.map((item) => <article key={item.id} className="oracle-ledger-row"><div><p className="text-xs font-bold text-[var(--oracle-text-primary)]">{item.statement}</p><p className="mt-1 oracle-technical text-[var(--oracle-text-muted)]">{humanize(item.relatedVariable)} · {humanize(item.impactIfChanged)} impact</p></div><OracleStateBadge state="ASSUMED" label={humanize(item.source)} compact /></article>) : <p className="text-xs text-[var(--oracle-text-muted)]">No assumptions provided.</p>}</div></div></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><OracleDataEvidenceSection dataCoverage={data.decisionDNA.dataCoverage} evidenceClassification={data.decisionDNA.evidenceConfidence.classification} evidenceMeasurements={data.decisionDNA.evidenceConfidence.measurements} overallSufficiencyStatus={data.dataSufficiency?.overallStatus} /><OracleUnknownVariablesSection criticalUnknownVariables={data.dataSufficiency?.criticalUnknownVariables || []} unknownCount={coverage.unknownVariableCount} notProvidedCount={coverage.notProvidedVariableCount} /></div></section>

        <section id="dossier-trajectories" className="scroll-mt-28"><SectionHeader number="11" eyebrow="Conditional trajectories" title="Branch the conditions, not the certainty." description="Base, Upside, and Downside Stress are conditional contracts. Selecting a branch highlights its existing assumptions, constraints, outcomes, and milestones without implying probability." /><div className="mt-7"><OracleTrajectoryExplorer scenarios={data.scenarios} onInspectProvenance={onInspectProvenance} selectedScenarioType={selectedScenarioType} onSelectScenarioType={onSelectScenarioType} selectedMilestoneId={selectedMilestoneId} onSelectMilestone={onSelectMilestone} /></div></section>

        <section id="dossier-temporal" className="scroll-mt-28"><SectionHeader number="12" eyebrow="Temporal milestones" title="Time is part of the instrument." description="Milestones are rendered from the selected scenario contract. Dates, events, capital states, and constraints remain exactly as supplied." /><div className="mt-7 grid gap-6 lg:grid-cols-[minmax(0,1fr)_280px]"><div className="oracle-instrument-surface"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="oracle-kicker">Selected conditional path</p><p className="mt-1 text-sm font-extrabold text-[var(--oracle-text-primary)]">{activeScenario.label} / {humanize(activeScenario.contract.dataSufficiency)}</p></div><OracleStateBadge state="CALCULATED" label={`${activeScenario.contract.temporalMilestones.length} milestones`} compact /></div><OracleTimelineRail points={milestonePoints} label={`${activeScenario.label} milestone rail`} onSelect={onSelectMilestone} className="mt-6" /></div><div className="oracle-instrument-surface"><OracleMetricSignal label="Horizon" value={formatNumber(activeScenario.contract.horizonMonths, " months")} state="KNOWN" accent="temporal" detail="Scenario contract horizon." /><OracleMetricSignal className="mt-4" label="Selected milestone" value={selectedMilestoneId || "None selected"} accent="action" detail="Select a marker to coordinate the dossier." /></div></div><div className="mt-7"><OracleTemporalTimeline scenarios={data.scenarios} selectedScenarioType={selectedScenarioType} selectedMilestoneId={selectedMilestoneId} onSelectMilestone={onSelectMilestone} onInspectProvenance={onInspectProvenance} /></div></section>

        <section id="dossier-provenance" className="scroll-mt-28"><SectionHeader number="13" eyebrow="Provenance / calculation record" title="Open the instrument’s technical record." description="These identifiers explain where the dossier came from without pretending that a hash is a decision score." /><div className="mt-7 oracle-provenance-record"><div className="flex flex-wrap items-center justify-between gap-4"><OracleProvenanceBadge label="Server-authoritative calculation boundary" methodologyVersion={data.auditTrail.dnaMethodologyVersion} /><span className="oracle-technical text-[var(--oracle-text-muted)]">{formatDate(data.auditTrail.serverEvaluatedAt)}</span></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="oracle-hash-field"><span>DNA SHA-256</span><code>{data.auditTrail.dnaComputationHash}</code></div><div className="oracle-hash-field"><span>BASE CASE SHA-256</span><code>{data.auditTrail.scenarioComputationHashes.baseCase}</code></div><div className="oracle-hash-field"><span>DOWNSIDE STRESS SHA-256</span><code>{data.auditTrail.scenarioComputationHashes.downsideStressCase}</code></div><div className="oracle-hash-field"><span>UPSIDE SHA-256</span><code>{data.auditTrail.scenarioComputationHashes.upsideCase}</code></div></div><button type="button" className="mt-5 inline-flex min-h-[40px] items-center gap-2 text-xs font-bold text-[var(--oracle-action)] hover:underline" onClick={() => onInspectProvenance("Dossier overview", data.auditTrail.dnaComputationHash)}><Hash className="h-4 w-4" />Open full provenance record</button></div></section>

        <section id="dossier-final" className="scroll-mt-28"><SectionHeader number="14" eyebrow="Final decision reading" title="Brief the structure, not the person." description="The closing reading uses only existing classifications, explicit unknowns, divergence factors, and recorded constraints." /><div className="mt-7 grid gap-4 lg:grid-cols-2"><OracleBoundaryMarker label="What the structure says" value={`${data.decisionDNA.financialExposure.semanticDirection} / ${data.decisionDNA.reversibility.semanticDirection} / ${data.decisionDNA.resourceFit.semanticDirection}`} description="Three existing dimension directions, not a recommendation." tone="action" /><OracleBoundaryMarker label="What remains unknown" value={coverage.criticalUnknownVariables.length ? coverage.criticalUnknownVariables.join(" · ") : `${coverage.unknownVariableCount} unknown / ${coverage.notProvidedVariableCount} not provided`} description="The dossier keeps missing information explicit." tone="unknown" /><OracleBoundaryMarker label="What would change the reading" value={data.scenarios.comparisonMatrix.divergenceFactors.join(" · ") || "No divergence factors provided"} description="Existing scenario divergence factors only." tone="temporal" /><OracleBoundaryMarker label="Conditions to watch" value={data.scenarios.baseCase.activeConstraints.map((constraint) => constraint.statement).join(" · ") || "No active constraints provided"} description="Existing base-case constraints only." tone="risk" /></div><div className="mt-7 flex flex-col justify-between gap-5 border-t border-[var(--oracle-border-strong)] pt-6 sm:flex-row sm:items-center"><div className="flex items-center gap-2 text-xs text-[var(--oracle-text-secondary)]"><CheckCircle2 className="h-4 w-4 text-[var(--oracle-provenance)]" />The next action remains yours; ORACLE preserves the structure and its boundaries.</div><button type="button" className="inline-flex min-h-[44px] items-center gap-2 text-xs font-bold text-[var(--oracle-action)] hover:underline" onClick={() => onSwitchView("what-if")}><ArrowUpRight className="h-4 w-4" />Explore a controlled What-If adjustment</button></div></section>
      </main>
    </div>
  );
};
