/** Evidence Ledger modal shell: preserves close behavior and adds keyboard focus containment for dialogs. */
import React, { useEffect, useRef } from "react";
import { AnimatePresence, motion } from "motion/react";
import { X } from "lucide-react";

export interface OracleModalProps { isOpen: boolean; onClose: () => void; title?: string; subtitle?: string; children: React.ReactNode; footer?: React.ReactNode; maxWidth?: "sm" | "md" | "lg" | "xl"; }
export const OracleModal: React.FC<OracleModalProps> = ({ isOpen, onClose, title, subtitle, children, footer, maxWidth = "md" }) => {
  const dialogRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const handleKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape" && isOpen) onClose(); if (event.key === "Tab" && isOpen && dialogRef.current) { const focusable = Array.from(dialogRef.current.querySelectorAll<HTMLElement>('button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])')) as HTMLElement[]; if (!focusable.length) return; const first = focusable[0]; const last = focusable[focusable.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } } }; if (isOpen) { document.body.style.overflow = "hidden"; window.addEventListener("keydown", handleKeyDown); window.setTimeout(() => dialogRef.current?.querySelector<HTMLElement>("button, [href], input, select, textarea")?.focus(), 0); } else document.body.style.overflow = ""; return () => { document.body.style.overflow = ""; window.removeEventListener("keydown", handleKeyDown); }; }, [isOpen, onClose]);
  const maxClasses = { sm: "max-w-md", md: "max-w-lg", lg: "max-w-2xl", xl: "max-w-4xl" };
  return <AnimatePresence>{isOpen && <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6" role="dialog" aria-modal="true"><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.2 }} onClick={onClose} className="fixed inset-0 bg-[color:rgba(23,32,40,.52)]" /><motion.div ref={dialogRef} initial={{ opacity: 0, scale: 0.96, y: 8 }} animate={{ opacity: 1, scale: 1, y: 0 }} exit={{ opacity: 0, scale: 0.96, y: 8 }} transition={{ duration: 0.2, ease: [0.23, 1, 0.32, 1] }} className={`relative z-10 flex max-h-[90vh] w-full ${maxClasses[maxWidth]} flex-col overflow-hidden border border-[var(--oracle-border-strong)] bg-[var(--oracle-canvas)] shadow-2xl`}><div className="flex shrink-0 items-center justify-between border-b border-[var(--oracle-border)] bg-[var(--oracle-surface)] px-6 py-5"><div>{title && <h3 className="text-base font-extrabold text-[var(--oracle-text-primary)]">{title}</h3>}{subtitle && <p className="mt-0.5 text-xs text-[var(--oracle-text-secondary)]">{subtitle}</p>}</div><button type="button" onClick={onClose} aria-label="Close modal" className="grid h-11 w-11 place-items-center border border-transparent text-[var(--oracle-text-secondary)] hover:border-[var(--oracle-border)] hover:bg-[var(--oracle-surface-subtle)] hover:text-[var(--oracle-text-primary)]"><X className="h-4 w-4" /></button></div><div className="flex-1 overflow-y-auto p-6">{children}</div>{footer && <div className="flex shrink-0 items-center justify-end gap-3 border-t border-[var(--oracle-border)] bg-[var(--oracle-surface)] px-6 py-4">{footer}</div>}</motion.div></div>}</AnimatePresence>;
};
