/** Evidence Ledger drawer shell: preserves escape, backdrop-close, motion, and focus-safe overflow behavior. */
import React, { useEffect } from "react";
import { AnimatePresence, motion } from "motion/react";
import { X } from "lucide-react";

export interface OracleDrawerProps { isOpen: boolean; onClose: () => void; title: string; subtitle?: string; children: React.ReactNode; footer?: React.ReactNode; width?: "sm" | "md" | "lg" | "xl"; }
export const OracleDrawer: React.FC<OracleDrawerProps> = ({ isOpen, onClose, title, subtitle, children, footer, width = "md" }) => {
  useEffect(() => { const handleKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape" && isOpen) onClose(); }; if (isOpen) { document.body.style.overflow = "hidden"; window.addEventListener("keydown", handleKeyDown); } else document.body.style.overflow = ""; return () => { document.body.style.overflow = ""; window.removeEventListener("keydown", handleKeyDown); }; }, [isOpen, onClose]);
  const widthClasses = { sm: "max-w-md", md: "max-w-xl", lg: "max-w-2xl", xl: "max-w-4xl" };
  return <AnimatePresence>{isOpen && <div className="fixed inset-0 z-50 flex justify-end" role="dialog" aria-modal="true"><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.2 }} onClick={onClose} className="fixed inset-0 bg-[color:rgba(23,32,40,.48)]" /><motion.div initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }} transition={{ duration: 0.25, ease: [0.23, 1, 0.32, 1] }} className={`relative z-10 flex h-full w-full ${widthClasses[width]} flex-col justify-between overflow-hidden border-l border-[var(--oracle-border-strong)] bg-[var(--oracle-canvas)] shadow-2xl`}><div className="flex shrink-0 items-center justify-between border-b border-[var(--oracle-border)] bg-[var(--oracle-surface)] px-6 py-5"><div><h3 className="text-base font-extrabold text-[var(--oracle-text-primary)]">{title}</h3>{subtitle && <p className="mt-0.5 text-xs text-[var(--oracle-text-secondary)]">{subtitle}</p>}</div><button type="button" onClick={onClose} aria-label="Close drawer" className="grid h-11 w-11 place-items-center border border-transparent text-[var(--oracle-text-secondary)] hover:border-[var(--oracle-border)] hover:bg-[var(--oracle-surface-subtle)] hover:text-[var(--oracle-text-primary)]"><X className="h-4 w-4" /></button></div><div className="flex-1 space-y-6 overflow-y-auto p-6">{children}</div>{footer && <div className="shrink-0 border-t border-[var(--oracle-border)] bg-[var(--oracle-surface)] px-6 py-4">{footer}</div>}</motion.div></div>}</AnimatePresence>;
};
